# .streamlit/secrets.toml

[openai]
api_key = "sk-YOUR_OPENAI_API_KEY"

# Thông tin service account của Google Cloud Platform (dưới dạng JSON)
# Copy toàn bộ nội dung file JSON của bạn vào đây
[gcp_service_account]
type = "service_account"
project_id = "your-gcp-project-id"
private_key_id = "your-private-key-id"
private_key = "-----BEGIN PRIVATE KEY-----\nYOUR_PRIVATE_KEY\n-----END PRIVATE KEY-----\n"
client_email = "your-service-account-email@your-gcp-project-id.iam.gserviceaccount.com"
client_id = "your-client-id"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"

# Tên Google Sheet của bạn
[google_sheets]
spreadsheet_name = "GA_Prompting_DB"
